(function (global) {
  const ITEM_SPECS = [
    {
      id: 'glow',
      name: 'Glow',
      type: 'level',
      maxLevel: 3,
      price: 20,
      minLevel: 2,
      notes: 'Active: +5% catch radius per level with glow visuals (already wired).',
    },
    {
      id: 'buds',
      name: 'Buds',
      type: 'level',
      maxLevel: 5,
      price: 10,
      minLevel: 2,
      notes: 'Visual companion orbs; plan to orbit smoothly around body and add small utility bonus per tier.',
    },
    {
      id: 'plusjump',
      name: '+Jump',
      type: 'single',
      price: 100,
      minLevel: 2,
      notes: 'Active: grants one extra air jump while free.',
    },
    {
      id: 'fly',
      name: 'Fly',
      type: 'single',
      price: 100,
      minLevel: 2,
      notes: 'Active: enables long-press flight once per run.',
    },
    {
      id: 'big',
      name: 'Big',
      type: 'level',
      price: 20,
      minLevel: 5,
      notes: 'Active: scales body size by +2.5% per level; price scales on purchase.',
    },
    {
      id: 'gamble',
      name: 'Gamble',
      type: 'consumable',
      price: 10,
      minLevel: 1,
      notes: 'Consumable: auto-activates for the next run, payout x1.5 then clears.',
    },
    {
      id: 'web',
      name: 'Web',
      type: 'consumable',
      price: 3,
      minLevel: 1,
      notes: 'Consumable: emergency web shot during free fall, clears after each run.',
    },
    {
      id: 'magnet',
      name: 'Magnet',
      type: 'level',
      maxLevel: 5,
      price: 30,
      minLevel: 3,
      notes: 'Extends pickup radius by +10px per level and pulls boxes toward the player.',
    },
    {
      id: 'shield',
      name: 'Shield',
      type: 'consumable',
      price: 100,
      minLevel: 4,
      notes: 'Consumable: plan to spend charge on rope snap to prevent break (per run).',
    },
    {
      id: 'combo',
      name: 'Combo+',
      type: 'level',
      maxLevel: 3,
      price: 80,
      minLevel: 6,
      notes: 'TODO: apply +0.5 combo multiplier per level when scoring combo catches.',
    },
    {
      id: 'slow',
      name: 'Slow',
      type: 'consumable',
      price: 100,
      minLevel: 3,
      notes: 'Consumable: plan to auto-trigger slow-mo when falling, clears per run.',
    },
    {
      id: 'double',
      name: 'Double',
      type: 'single',
      price: 100,
      minLevel: 8,
      notes: 'TODO: boost rope detach power by ~1.3x while active.',
    },
    {
      id: 'lucky',
      name: 'Lucky',
      type: 'level',
      maxLevel: 5,
      price: 40,
      minLevel: 2,
      notes: 'TODO: increase item spawn probability by +5% per level.',
    },
    {
      id: 'revival',
      name: 'Revival',
      type: 'consumable',
      price: 100,
      minLevel: 10,
      notes: 'Consumable: plan to auto-revive once on ground impact, clears per run.',
    },
    {
      id: 'rainbow',
      name: 'Rainbow',
      type: 'single',
      price: 30,
      minLevel: 3,
      notes: 'TODO: apply animated rainbow tint to player body and trail.',
    },
    {
      id: 'fever',
      name: 'Fever+',
      type: 'level',
      maxLevel: 3,
      price: 60,
      minLevel: 5,
      notes: 'TODO: extend star mode duration by +2 seconds per level.',
    },
    {
      id: 'bank',
      name: 'Bank',
      type: 'level',
      maxLevel: 5,
      price: 100,
      minLevel: 1,
      notes: 'TODO: grant +10% earnings interest per level at run end.',
    },
  ];

  global.ITEM_SPECS = ITEM_SPECS;
})(typeof window !== 'undefined' ? window : globalThis);
