(function (global) {
  const ITEM_SPECS = [
    { id: 'glow', type: 'level', maxLevel: 3, price: 20, minLevel: 2, unlock: { type: 'level', value: 2 } },
    { id: 'buds', type: 'level', maxLevel: 5, price: 10, minLevel: 2, unlock: { type: 'level', value: 2 } },
    { id: 'plusjump', type: 'single', price: 100, minLevel: 2, unlock: { type: 'level', value: 2 } },
    { id: 'fly', type: 'single', price: 100, minLevel: 2, unlock: { type: 'level', value: 2 } },
    { id: 'big', type: 'level', price: 20, minLevel: 5, unlock: { type: 'level', value: 5 } },
    { id: 'gamble', type: 'consumable', price: 10, minLevel: 1, unlock: { type: 'level', value: 1 } },
    { id: 'web', type: 'consumable', price: 3, minLevel: 1, unlock: { type: 'level', value: 1 } },
    { id: 'magnet', type: 'level', maxLevel: 5, price: 30, minLevel: 3, unlock: { type: 'level', value: 3 } },
    { id: 'combo', type: 'level', maxLevel: 3, price: 80, minLevel: 6, unlock: { type: 'level', value: 6 } },
    { id: 'slow', type: 'consumable', price: 100, minLevel: 3, unlock: { type: 'level', value: 3 } },
    { id: 'double', type: 'single', price: 100, minLevel: 8, unlock: { type: 'level', value: 8 } },
    { id: 'lucky', type: 'level', maxLevel: 5, price: 40, minLevel: 2, unlock: { type: 'level', value: 2 } },
    { id: 'revival', type: 'consumable', price: 100, minLevel: 10, unlock: { type: 'level', value: 10 } },
    { id: 'fever', type: 'level', maxLevel: 3, price: 60, minLevel: 5, unlock: { type: 'level', value: 5 } },
  ];

  const ITEM_ART = {
    glow: {
      palette: {
        '.': null,
        Y: '#ffe066',
        O: '#ff922b',
      },
      pixels: [
        '..YYYY..',
        '.YYYYYY.',
        '.YYOOYY.',
        'YYYYYYYY',
        '.YYOOYY.',
        '.YYYYYY.',
        '..YYYY..',
        '...YY...',
      ],
    },
    buds: {
      palette: {
        '.': null,
        L: '#9ef01a',
        G: '#4f772d',
        S: '#d9ed92',
      },
      pixels: [
        '...SS...',
        '..SLLS..',
        '.SLLLLS.',
        '..SLLS..',
        '...SS...',
        '..G..G..',
        '.GG..GG.',
        '........',
      ],
    },
    plusjump: {
      palette: {
        '.': null,
        A: '#ff9f1c',
        P: '#ffffff',
      },
      pixels: [
        '...A....',
        '..AAA...',
        '.AAPAA..',
        '...A....',
        '..PPP...',
        '.P.P.P..',
        '..PPP...',
        '........',
      ],
    },
    fly: {
      palette: {
        '.': null,
        B: '#4cc9f0',
        W: '#ffffff',
        N: '#4361ee',
      },
      pixels: [
        '..B..B..',
        '.BBB.BB.',
        'BBBBBBB.',
        '.BBBBB..',
        '..BBB...',
        '..NWN...',
        '...W....',
        '........',
      ],
    },
    big: {
      palette: {
        '.': null,
        C: '#adb5bd',
        O: '#ff6b6b',
      },
      pixels: [
        'CO....OC',
        'CCO..OCC',
        '.CCOOCC.',
        '..COOC..',
        '..COOC..',
        '.CCOOCC.',
        'CCO..OCC',
        'CO....OC',
      ],
    },
    gamble: {
      palette: {
        '.': null,
        D: '#ffffff',
        P: '#1b263b',
        G: '#ffd60a',
      },
      pixels: [
        '..DDDD..',
        '.DPPPPD.',
        '.DP..PD.',
        '.DPG.PD.',
        '.DP..PD.',
        '.DPPPPD.',
        '..DDDD..',
        '........',
      ],
    },
    web: {
      palette: {
        '.': null,
        W: '#ffffff',
        B: '#74c0fc',
      },
      pixels: [
        '.W....W.',
        '..W..W..',
        '.WWWWWW.',
        'W.WBB.WW',
        '.WWWWWW.',
        '..W..W..',
        '.W....W.',
        '........',
      ],
    },
    magnet: {
      palette: {
        '.': null,
        M: '#ff6b6b',
        N: '#4d908e',
        W: '#ffffff',
      },
      pixels: [
        '..MMMM..',
        '.M....M.',
        '.M....M.',
        '.MNNNNM.',
        '.MNNNNM.',
        '.MWWWWM.',
        '..MMMM..',
        '........',
      ],
    },
    combo: {
      palette: {
        '.': null,
        C: '#ffd166',
        O: '#f3722c',
      },
      pixels: [
        '.CC..CC.',
        'COC..COC',
        '.CC..CC.',
        '..CCCC..',
        '..COOC..',
        '..CCCC..',
        '.CC..CC.',
        '........',
      ],
    },
    slow: {
      palette: {
        '.': null,
        S: '#90a955',
        G: '#ffe066',
      },
      pixels: [
        'SSSSSSSS',
        'S.G..G.S',
        '.SG..GS.',
        '..SGGS..',
        '..SGGS..',
        '.SG..GS.',
        'S.G..G.S',
        'SSSSSSSS',
      ],
    },
    double: {
      palette: {
        '.': null,
        D: '#00b4d8',
        X: '#ff006e',
      },
      pixels: [
        '.DDDDDD.',
        '.D....D.',
        '...DD...',
        '..D..D..',
        '.D....D.',
        'DDDDDDDD',
        '.X....X.',
        '..XXXX..',
      ],
    },
    lucky: {
      palette: {
        '.': null,
        L: '#2b9348',
        S: '#55a630',
      },
      pixels: [
        '..LL.LL.',
        '.LLLLLL.',
        '.LLSSLL.',
        '..LLLL..',
        '...LL...',
        '..LLL...',
        '.LL.LL..',
        '........',
      ],
    },
    revival: {
      palette: {
        '.': null,
        R: '#ff4d6d',
        H: '#ff99ac',
        S: '#ffe066',
      },
      pixels: [
        '.RR..RR.',
        'RRRRRRRR',
        'RHHHHHRR',
        'RRHHHRRR',
        '.RRRRR..',
        '..RRR...',
        '...S....',
        '........',
      ],
    },
    fever: {
      palette: {
        '.': null,
        F: '#ffbe0b',
        O: '#fb5607',
        R: '#ff006e',
      },
      pixels: [
        '...F....',
        '..FFF...',
        '.FFFFF..',
        'FFFOFFF.',
        '.FFFFF..',
        '..FFF...',
        '..FRF...',
        '...R....',
      ],
    },
  };

  global.ITEM_SPECS = ITEM_SPECS;
  global.ITEM_ART = ITEM_ART;
})(typeof window !== 'undefined' ? window : globalThis);
