(function (global) {
  const ITEM_SPECS = [
    {
      id: 'glow',
      name: 'Glow',
      type: 'level',
      maxLevel: 3,
      price: 20,
      minLevel: 2,
      notes: 'Active: +5% catch radius per level with glow visuals (already wired).',
    },
    {
      id: 'buds',
      name: 'Buds',
      type: 'level',
      maxLevel: 5,
      price: 10,
      minLevel: 2,
      notes: 'Visual companion orbs; plan to orbit smoothly around body and add small utility bonus per tier.',
    },
    {
      id: 'plusjump',
      name: '+Jump',
      type: 'single',
      price: 100,
      minLevel: 2,
      notes: 'Active: grants one extra air jump while free.',
    },
    {
      id: 'fly',
      name: 'Fly',
      type: 'single',
      price: 100,
      minLevel: 2,
      notes: 'Active: enables long-press flight once per run.',
    },
    {
      id: 'big',
      name: 'Big',
      type: 'level',
      price: 20,
      minLevel: 5,
      notes: 'Active: scales body size by +2.5% per level; price scales on purchase.',
    },
    {
      id: 'gamble',
      name: 'Gamble',
      type: 'consumable',
      price: 10,
      minLevel: 1,
      notes: 'Consumable: auto-activates for the next run, payout x1.5 then clears.',
    },
    {
      id: 'web',
      name: 'Web',
      type: 'consumable',
      price: 3,
      minLevel: 1,
      notes: 'Consumable: emergency web shot during free fall, clears after each run.',
    },
    {
      id: 'magnet',
      name: 'Magnet',
      type: 'level',
      maxLevel: 5,
      price: 30,
      minLevel: 3,
      notes: 'Extends pickup radius by +10px per level and pulls nearby boxes inward.',
    },
    {
      id: 'combo',
      name: 'Combo+',
      type: 'level',
      maxLevel: 3,
      price: 80,
      minLevel: 6,
      notes: 'Active: combo catches grant +0.5x bonus per level.',
    },
    {
      id: 'slow',
      name: 'Slow',
      type: 'consumable',
      price: 100,
      minLevel: 3,
      notes: 'Consumable: auto slow-mo triggers on falls (up to 3 uses).',
    },
    {
      id: 'double',
      name: 'Double',
      type: 'single',
      price: 100,
      minLevel: 8,
      notes: 'Active: rope detach boost 1.3x stronger.',
    },
    {
      id: 'lucky',
      name: 'Lucky',
      type: 'level',
      maxLevel: 5,
      price: 40,
      minLevel: 2,
      notes: 'Active: +5% box spawn chance per level.',
    },
    {
      id: 'revival',
      name: 'Revival',
      type: 'consumable',
      price: 100,
      minLevel: 10,
      notes: 'Consumable: auto rescue rope on ground impact (one use).',
    },
    {
      id: 'fever',
      name: 'Fever+',
      type: 'level',
      maxLevel: 3,
      price: 60,
      minLevel: 5,
      notes: 'Level: star mode lasts +2s per level.',
    },
  ];

  global.ITEM_SPECS = ITEM_SPECS;
})(typeof window !== 'undefined' ? window : globalThis);
